#!/usr/bin/env php
<?php

use Telegram\Api;
use Telegram\Bot;
use Telegram\Config;
use Telegram\Database\Migrator;
use Telegram\Plugins\Database;
use Telegram\Terminal;

require_once __DIR__ . '/vendor/autoload.php';

$config = new Config(require_once __DIR__ . '/config/bot.php');

$api = new Api($config->bot['token']);
$bot = new Bot($api, $config);

$plugins = require_once __DIR__ . '/config/plugins.php';
$bot->plugins(arr_where($plugins, fn ($item) => $item['plugin'] == Database::class));

$migrator = new Migrator($bot);

switch (strtolower($argv[1] ?? '')) {
    case 'migrate':
            switch ($argv[2]) {
                case 'up':
                    $migrator->up('users');
                    Terminal::print('{text:darkGreen}✅ Migration was UP.');
                    break;

                case 'down':
                    if (mb_strtolower(Terminal::ask('Drop all Telegram tables?')) == 'y') {
                        $migrator->down('users');
                        Terminal::print('{text:darkGreen}✅ Migration was DOWN.');
                    } else {
                        Terminal::print('{text:yellow}Operation was canceled.');
                    }
                    break;

                default:
                    die('Bad parameter: php migration [up, down]');
            }
        break;

    default:
        die('php gram [migrate]');
        break;
}